import type { Project } from "@/types/project";

/** Real work — client builds, apps, and products by Pilk.ai. */
export const projects: Project[] = [
  {
    slug: "watchman",
    name: "Watchman",
    label: "App Build",
    category: "Mobile App + Marketing Site",
    year: "2025",
    accent: "#7c3aed",
    summary:
      "A full mobile app build with a matching marketing site — custom UI, native iOS & Android, and a complete brand and launch system.",
    services: ["App Design", "Development", "Brand", "Marketing Site"],
    cover: "/work/watchman.jpg",
    liveUrl: "https://thewatchman.app",
    cost: "$75,000",
  },
  {
    slug: "stephenie-tocado",
    name: "Stephenie Tocado",
    label: "Client Build",
    category: "Real Estate Agent",
    year: "2025",
    accent: "#1f6feb",
    summary:
      "A personal real-estate brand site — clean, modern, and built to capture qualified leads.",
    services: ["Design", "Development", "Lead Capture"],
    cover: "/showcase-sites/stephenie-tocado/desktop.jpg",
  },
  {
    slug: "star-processing",
    name: "Star Processing",
    label: "Client Build",
    category: "Loan Processing",
    year: "2025",
    accent: "#2563eb",
    summary:
      "A credible, conversion-focused website for a third-party loan-processing company.",
    services: ["Design", "Development", "Conversion"],
    cover: "/showcase-sites/star-processing/desktop.jpg",
    liveUrl: "https://www.star-processing.com",
  },
  {
    slug: "ballantyne-title",
    name: "Ballantyne Title",
    label: "Client Build",
    category: "Title — JV",
    year: "2025",
    accent: "#0f766e",
    summary: "A trust-driven title company site built for a joint venture.",
    services: ["Design", "Development"],
    cover: "/showcase-sites/ballantyne-title/desktop.jpg",
  },
  {
    slug: "carnegie-title",
    name: "Carnegie Title",
    label: "Client Build",
    category: "Title",
    year: "2025",
    accent: "#b08d57",
    summary: "A clean, professional title-company website focused on quotes and services.",
    services: ["Design", "Development"],
    cover: "/showcase-sites/carnegie-title/desktop.jpg",
  },
  {
    slug: "refine-title",
    name: "Refine Title",
    label: "Client Build",
    category: "Title",
    year: "2025",
    accent: "#3b82f6",
    summary: "A modern title-company brand and website built to convert.",
    services: ["Design", "Development"],
    cover: "/showcase-sites/refine-title/desktop.jpg",
  },
  {
    slug: "stage-echo",
    name: "Stage Echo",
    label: "Client Build",
    category: "Events & Entertainment",
    year: "2025",
    accent: "#9d6bff",
    summary: "A bold brand and site for an events and entertainment company.",
    services: ["Brand", "Design", "Development"],
    cover: "/showcase-sites/stage-echo/desktop.jpg",
  },
  {
    slug: "famlink",
    name: "FamLink",
    label: "App Build",
    category: "Mobile App",
    year: "2025",
    accent: "#5b54c9",
    summary: "A clean, modern mobile app — custom interface, fluid motion, iOS & Android.",
    services: ["App Design", "Development"],
    cover: "/work/famlink.jpg",
  },
  {
    slug: "chrome-hurt",
    name: "Chrome Hurt",
    label: "Brand Build",
    category: "Art / Brand",
    year: "2025",
    accent: "#8b5cf6",
    summary:
      "A high-concept brand and controlled-access drop experience built around mystery and exclusivity.",
    services: ["Brand", "Design", "Development"],
    cover: "/work/chrome-hurt.jpg",
  },
  {
    slug: "uncapped-poker",
    name: "Uncapped Poker",
    label: "App Build",
    category: "App / Product",
    year: "2025",
    accent: "#1f7a6b",
    summary: "A product and app build for a modern poker brand.",
    services: ["Product Design", "Development"],
    cover: "/work/uncapped-poker.jpg",
  },
  {
    slug: "course-ai",
    name: "Course AI",
    label: "Platform Build",
    category: "Learning Platform",
    year: "2025",
    accent: "#2563eb",
    summary: "An AI-powered course and learning platform.",
    services: ["Product", "Development", "AI"],
    cover: "/work/course-ai.jpg",
  },
  {
    slug: "rolodex-ai",
    name: "Rolodex AI",
    label: "Platform Build",
    category: "AI CRM",
    year: "2025",
    accent: "#7c3aed",
    summary: "An AI-driven contact and relationship tool.",
    services: ["Product", "Development", "AI"],
    cover: "/work/rolodex-ai.jpg",
  },
  {
    slug: "brandgen",
    name: "Brandgen",
    label: "Software Build",
    category: "AI Desktop App",
    year: "2025",
    accent: "#6d5bd0",
    summary: "A desktop AI assistant application.",
    services: ["Software", "Development", "AI"],
    cover: "/work/brandgen.jpg",
  },
  {
    slug: "home-with-richard",
    name: "Home With Richard",
    label: "Client Build",
    category: "Real Estate Agent",
    year: "2025",
    accent: "#1f6feb",
    summary: "A personal real-estate brand site for an individual agent.",
    services: ["Design", "Development", "Lead Capture"],
    cover: "/work/home-with-richard.jpg",
  },
  {
    slug: "bubble-down",
    name: "Bubble Down",
    label: "App Build",
    category: "Car Wash Membership App",
    year: "2025",
    accent: "#38bdf8",
    summary:
      "A premium, mobile-first membership app for a Tampa Bay car wash — native iOS & Android, memberships, rewards, and a live map.",
    services: ["App Design", "Development", "Brand"],
    cover: "/work/bubble-down.jpg",
  },
  {
    slug: "agency-os",
    name: "Agency OS",
    label: "Platform Build",
    category: "Google Ads AI Platform",
    year: "2025",
    accent: "#8b5cf6",
    summary:
      "An internal operating system managing ~50 Google Ads accounts — AI scoring, alerts, automated client reports, and an approval queue.",
    services: ["Product", "Development", "AI", "Automation"],
    cover: "/work/agency-os.jpg",
  },
  {
    slug: "ecrn",
    name: "ECRN",
    label: "Platform Build",
    category: "Referral Network PWA",
    year: "2025",
    accent: "#2563eb",
    summary:
      "A mobile-first referral network for the construction industry — partner referrals, candidate applications, payouts, and an admin dashboard.",
    services: ["Product", "Development", "PWA"],
    cover: "/work/ecrn.jpg",
  },
];

export function getProject(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}
